---
- name: Download Flannel manifest file
  get_url:
    url: "{{ kubernetes_flannel_manifest_file }}"
    dest: "/tmp/{{ kubernetes_flannel_manifest_file | basename }}"
  register: download_file
  until: download_file is succeeded
  retries: 3
  delay: 2

# 如果Node有多个网卡的话，参考flannel issues 39701，
# 目前需要在kube-flannel.yml中使用--iface参数指定集群主机内网网卡的名称，否则可能会出现dns无法解析。
- name: Get interface name of apiserver advertise address
  shell: ifconfig | grep -B1 "inet addr:{{ kubernetes_apiserver_advertise_address }}" | awk '$1!="inet" && $1!="--" {print $1}'
  changed_when: false
  register: iface_result
  when: kubernetes_apiserver_advertise_address is defined

- name: Update Flannel manifest file
  shell: |
    grep -q '^\s*- --iface=' /tmp/{{ kubernetes_flannel_manifest_file | basename }} &&
      sed -i 's|^\(\s*\)- --iface=.*|\1- --iface={{ iface_result.stdout }}|g' /tmp/{{ kubernetes_flannel_manifest_file | basename }} ||
      sed -i '/^\(\s*\)- --kube-subnet-mgr/a\
            - --iface={{ iface_result.stdout }}' /tmp/{{ kubernetes_flannel_manifest_file | basename }}
  when: kubernetes_apiserver_advertise_address is defined

- name: Configure Flannel networking
  command: kubectl apply -f /tmp/{{ kubernetes_flannel_manifest_file | basename }}
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"
  become: true