---
- name: Check is Helm installed
  shell: command -v helm >/dev/null 2>&1
  register: helm_is_installed
  ignore_errors: yes
  changed_when: false
  become: true

- name: Gather currently installed Helm version
  shell: helm version --client | awk -F'"' '{print $2}'
  changed_when: false
  register: helm_current_version
  become: true
  when: helm_is_installed.rc == 0

- name: Install tiller (only for helm v2)
  include_tasks: install-tiller.yml
  when:
    - helm_is_installed.rc == 0
    - helm_current_version.stdout.split('.')[0] == 'v2'

- import_tasks: add-helm-repos.yml

- name: Migrate helm releases
  include_tasks: migrate-helm-releases.yml
  when: kubernetes_helm_migrate_releases | bool
