---
- name: Check if hostpath-provisioner is installed
  shell: helm list hostpath-provisioner --deployed
  register: helm_status
  changed_when: false
  become: true

- block:
    - name: Download hostpath-provisioner chart
      shell: helm fetch rimusz/hostpath-provisioner --version {{ kubernetes_hostpath_provisioner_version }} -d /tmp

    - name: Install hostpath-provisioner
      shell: >
        helm upgrade -i hostpath-provisioner /tmp/hostpath-provisioner-{{ kubernetes_hostpath_provisioner_version }}.tgz
          --namespace kube-system --wait --force --recreate-pods
  become: true
  when: helm_status.stdout == ""
