---
- name: Check if nfs-client-provisioner is installed
  shell: helm list --deployed {% if helm_current_version.stdout.split('.')[0] != 'v2' %}--all-namespaces{% endif %} | grep '^nfs-client-provisioner\s' | wc -l
  register: install_status
  changed_when: false
  become: true

- block:
    - name: Download nfs-client-provisioner chart
      shell: helm fetch stable/nfs-client-provisioner --version {{ kubernetes_nfs_client_provisioner_version }} -d /tmp

    - name: Copy nfs-client-provisioner vlaues file
      template:
        src: nfs-client-provisioner-values.yml.j2
        dest: /tmp/nfs-client-provisioner-values.yml

    - name: Install nfs-client-provisioner
      shell: |
        helm upgrade -i nfs-client-provisioner /tmp/nfs-client-provisioner-{{ kubernetes_nfs_client_provisioner_version }}.tgz \
          -f /tmp/nfs-client-provisioner-values.yml \
          --namespace kube-system --force --wait
      register: install_result

    - name: Print the install output to screen
      debug:
        msg: "{{ install_result.stdout_lines }}"
  become: true
  when: (install_status.stdout == '0') or (kubernetes_upgrade_nfs_client_provisioner | bool)
