---
- name: Check if nginx-ingress is installed
  shell: helm list nginx-ingress --deployed
  register: helm_status
  changed_when: false
  become: true

- block:
    - name: Download nginx-ingress chart
      shell: helm fetch stable/nginx-ingress --version {{ kubernetes_nginx_ingress_version }} -d /tmp

    - name: Copy nginx-ingress vlaues file
      template:
        src: nginx-ingress-values.yml.j2
        dest: /tmp/nginx-ingress-values.yml

    - name: Install nginx-ingress
      shell: >
        helm upgrade -i -f /tmp/nginx-ingress-values.yml nginx-ingress /tmp/nginx-ingress-{{ kubernetes_nginx_ingress_version }}.tgz
          --namespace kube-system --wait --force --recreate-pods
  become: true
  when: helm_status.stdout == ""
