---
- name: Check if nginx-ingress is installed
  shell: helm list --deployed {% if helm_current_version.stdout.split('.')[0] != 'v2' %}--all-namespaces{% endif %} | grep '^nginx-ingress\s' | wc -l
  register: install_status
  changed_when: false
  become: true

- block:
    - name: Download nginx-ingress chart
      shell: helm fetch stable/nginx-ingress --version {{ kubernetes_nginx_ingress_version }} -d /tmp

    - name: Copy nginx-ingress vlaues file
      template:
        src: nginx-ingress-values.yml.j2
        dest: /tmp/nginx-ingress-values.yml

    - name: Install nginx-ingress
      shell: |
        helm upgrade -i nginx-ingress /tmp/nginx-ingress-{{ kubernetes_nginx_ingress_version }}.tgz \
          -f /tmp/nginx-ingress-values.yml \
          --namespace kube-system --force
      register: install_result

    - name: Print the install output to screen
      debug:
        msg: "{{ install_result.stdout_lines }}"
  become: true
  when: (install_status.stdout == '0') or (kubernetes_upgrade_nginx_ingress | bool)
