---
- name: Check if hostpath-provisioner is installed
  shell: helm list hostpath-provisioner --deployed
  register: helm_status
  changed_when: false
  become: true

- block:
    - name: Add rimusz helm repo
      shell: helm repo add rimusz https://charts.rimusz.net
      become: true

    - name: Update helm repo
      shell: helm repo update
      become: true

    - name: Install hostpath-provisioner
      shell: >
        helm upgrade -i hostpath-provisioner rimusz/hostpath-provisioner --namespace kube-system --wait --force --recreate-pods
      retries: 5
      delay: 3
      register: result
      until: result.rc == 0
  when: helm_status.stdout == ""
