---
- name: Check if hostpath-provisioner is installed
  shell: helm list nginx-ingress --deployed
  register: helm_status
  changed_when: false
  become: true

- block:
    - name: Add stable helm repo
      shell: helm repo add stable https://charts.rimusz.net
      become: true

    - name: Update helm repo
      shell: helm repo update
      become: true

    - name: Download hostpath-provisioner chart
      shell: helm fetch stable/nginx-ingress --version 1.41.2 -d /tmp
      become: true

    - name: Install hostpath-provisioner
      shell: >
        helm upgrade -i hostpath-provisioner /tmp/hostpath-provisioner-0.2.9.tgz --namespace kube-system --wait --force --recreate-pods
  when: helm_status.stdout == ""
