---
- name: Check if hostpath-provisioner is installed
  command: helm status hostpath-provisioner >/dev/null 2>&1
  register: helm_status
  ignore_errors: yes
  changed_when: false
  become: true

- name: Add rimusz Helm repo
  command: helm repo add rimusz https://charts.rimusz.net
  become: true

- name: Install hostpath-provisioner
  command: >
    helm install --name hostpath-provisioner rimusz/hostpath-provisioner --namespace kube-system
  when: helm_status.rc != 0
