---
- name: Check if metrics-server is installed
  shell: helm list metrics-server --deployed
  register: helm_status
  changed_when: false
  become: true

- block:
    - name: Download metrics-server chart
      shell: helm fetch stable/metrics-server --version {{ kubernetes_metrics_server_version }} -d /tmp

    - name: Copy metrics-serer vlaues file
      template:
        src: metrics-server-values.yml.j2
        dest: /tmp/metrics-server-values.yml

    - name: Install metrics-server
      shell: |
        helm upgrade -i metrics-server /tmp/metrics-server-{{ kubernetes_metrics_server_version }}.tgz \
          -f /tmp/metrics-server-values.yml \
          --namespace kube-system --force --recreate-pods
      register: install_result

    - name: Print the install output to screen
      debug:
        msg: "{{ install_result.stdout_lines }}"
  become: true
  when: helm_status.stdout == ""
