---
- name: Check if hostpath-provisioner is installed
  shell: helm list --deployed | grep -q '^hostpath-provisioner '
  register: install_status
  changed_when: false
  become: true

- block:
    - name: Download hostpath-provisioner chart
      shell: helm fetch rimusz/hostpath-provisioner --version {{ kubernetes_hostpath_provisioner_version }} -d /tmp

    - name: Install hostpath-provisioner
      shell: |
        helm upgrade -i hostpath-provisioner /tmp/hostpath-provisioner-{{ kubernetes_hostpath_provisioner_version }}.tgz \
          --namespace kube-system --force
      register: install_result

    - name: Print the install output to screen
      debug:
        msg: "{{ install_result.stdout_lines }}"
  become: true
  when: install_status.rc != 0
