---
- include_tasks: prerequisites.yml

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- set_fact:
  kubernetes_init_stat: "{{ kubernetes_init_stat.stat.exists }}"

# Set up master.
- include_tasks: master-setup.yml
  when: kubernetes_role == 'master'