---
- import_tasks: prerequisites.yml

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Set up Kubernetes master
  include_tasks: master-setup.yml
  when: kubernetes_role == 'master'

- name: Get the kubeadm join command from the Kubernetes master
  command: kubeadm token create --print-join-command
  changed_when: false
  when: kubernetes_role == 'master'
  register: kubernetes_join_command_result

- name: Set the kubeadm join command globally
  set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }} {{ kubernetes_join_command_extra_opts }}
  delegate_to: "{{ host }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host
  when: kubernetes_join_command_result.stdout is defined

- name: Set up Kubernetes node
  include_tasks: node-setup.yml
  when: kubernetes_role == 'node'

- name: Init Helm
  include_tasks: init-helm.yml
  when: kubernetes_role == 'master'

- name: Install Kubernetes apps
  include_tasks: install-kubernetes-apps.yml
  when: kubernetes_role == 'master'
