---
- name: Initialize Kubernetes master with kubeadm init
  command: >
    kubeadm init
    {% if kubernetes_version is defined %}
    --kubernetes-version {{ kubernetes_version }}
    {% endif %}
    {% if kubernetes_apiserver_advertise_address is defined %}
    --apiserver-advertise-address={{ kubernetes_apiserver_advertise_address }}
    {% endif %}
    {% if kubernetes_ignore_preflight_errors is defined %}
    --ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }}
    {% endif %}
    --pod-network-cidr={{ kubernetes_pod_network.cidr }}
    {{ kubernetes_kubeadm_init_extra_opts }}
  register: kubeadmin_init
  become: true
  when: not kubernetes_init_stat.stat.exists

- name: Print the init output to screen
  debug:
    var: kubeadmin_init.stdout
    verbosity: 2
  when: not kubernetes_init_stat.stat.exists

- name: Ensure .kube directory exists
  file:
    path: ~/.kube
    state: directory

- name: Copy the kubectl admin.conf to ~/.kube/conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes
  become: true

- name: Configure Flannel networking
  command: kubectl apply -f {{ kubernetes_flannel_manifest_file }}
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"
  when: kubernetes_pod_network.cni == 'flannel'