---
- name: Initialize Kubernetes master with kubeadm init
  command: >
    kubeadm init
    --pod-network-cidr={{ kubernetes_pod_network.cidr }}
    {% if kubernetes_apiserver_advertise_address is defined %}
    --apiserver-advertise-address={{ kubernetes_apiserver_advertise_address }}
    {% endif %}
    {% if kubernetes_version is defined %}
    --kubernetes-version {{ kubernetes_version }}
    {% endif %}
    {{ kubernetes_kubeadm_init_extra_opts }}
  register: kubeadmin_init
  when: not kubernetes_init_stat.stat.exists

- debug: msg="{{ kubeadmin_init }}"
