---
- name: Initialize Kubernetes master with kubeadm init
  command: >
    kubeadm init
    {% if kubernetes_version is defined %}
    --kubernetes-version {{ kubernetes_version }}
    {% endif %}
    {% if kubernetes_apiserver_advertise_address is defined %}
    --apiserver-advertise-address={{ kubernetes_apiserver_advertise_address }}
    {% endif %}
    {% if kubernetes_ignore_preflight_errors is defined %}
    --ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }}
    {% endif %}
    --pod-network-cidr={{ kubernetes_pod_network.cidr }}
    {{ kubernetes_kubeadm_init_extra_opts }}
  register: kubeadmin_init
  become: true
  when: not kubernetes_init_stat

- name: Print the init output to screen
  debug:
    var: kubeadmin_init.stdout
    verbosity: 2
  when: not kubernetes_init_stat

- name: Ensure .kube directory exists
  file:
    path: ~/.kube
    state: directory
  become: true

- name: Symlink the kubectl admin.conf to ~/.kube/conf
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
  become: true

- name: Configure Flannel networking
  command: kubectl apply -f {{ kubernetes_flannel_manifest_file }}
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"
  when: kubernetes_pod_network.cni == 'flannel'
  become: true

- name: Configure Calico networking.
  command: kubectl apply -f {{ kubernetes_calico_manifest_file }}
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  when: kubernetes_pod_network.cni == 'calico'
  become: true

- name: Allow pods on master node (if configured)
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  when:
    - kubernetes_allow_pods_on_master | bool
    - not kubernetes_init_stat
  become: true
