---
- block:
    - name: Install 2to3 plugin
      shell: helm plugin install https://github.com/helm/helm-2to3.git
      register: result
      changed_when: "'Installed plugin: 2to3' in result.stderr"
      failed_when: "result.rc != 0 and 'already exists' not in result.stderr"

    - name: Get helm v2 releases
      shell: |
        kubectl get configmap -n kube-system -l "OWNER=TILLER" | awk '{print $1}' | \
          grep -v NAME | cut -d '.' -f1 | uniq
      register: helm_releases
      changed_when: false

    - name: Migrate helm v2 releases in-place to helm v3
      shell: |
        helm 2to3 convert {{ helm_release }}
      register: result
      changed_when: "'converted successfully' in result.stderr"
      failed_when: "result.rc != 0 and 'already exists' not in result.stderr"
      with_items:
        - "{{ helm_releases.stdout_lines }}"
      loop_control:
        loop_var: helm_release
  become: true
  when: helm_current_version.stdout.split('.')[0] > 'v2'

- debug: msg="{{ result }}"
