---
- name: Disable Swap
  shell: swapoff -a
  become: true

- name: Comment Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.* swap .*)'
    replace: '# \1'
  become: true

- name: mount all
  command: mount -a
  args:
    warn: no
  become: true