---
- name: Check the number of available CPUs
  assert:
    that:
      - ansible_processor_vcpus >= 2
    msg: "the number of available CPUs {{ ansible_processor_vcpus }} is less than the required 2"

- name: Check the size of total Memory
  assert:
    that:
      - ansible_memtotal_mb / 1000 | round >= 2
    msg: "the size of total Memory {{ ansible_memtotal_mb / 1000 | round }} is less than the required 2GB"

- debug: msg="{{ ansible_memtotal_mb }}" 

- name: Disable Swap
  shell: swapoff -a
  become: true

- name: Comment Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.* swap .*)'
    replace: '# \1'
  become: true