---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - curl
    state: present
  become: true

- name: Add Kubernetes’s official GPG key
  shell: >
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    warn: false
  become: true

- name: Add Kubernetes repository
  apt_repository:
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    update_cache: true
  become: true

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet{% if kubernetes_version != 'latest' %}={{ kubernetes_version }}*{% endif %}
      - kubeadm{% if kubernetes_version != 'latest' %}={{ kubernetes_version }}*{% endif %}
      - kubectl{% if kubernetes_version != 'latest' %}={{ kubernetes_version }}*{% endif %}
    state: present
  become: true
